services:
  admin-server:
    build:
      context: ./admin-server
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - my-network
  web-socket:
    build:
      context: ./web-socket
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s  # preventing multiple services from trying to bind to the same port simultaneously
    depends_on:
      - admin-server
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "DELAY_SERVICE_HOST=delay-service"
    networks:
      - my-network
  delay-service:
    build:
      context: ./delay-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s  # preventing multiple services from trying to bind to the same port simultaneously
    depends_on:
      - admin-server
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge